import { API_PREFIX } from "@/config/api"

export default {
    createEmailCode: API_PREFIX + '/user/create/email/code',
    createEmailUserVerify: API_PREFIX + '/user/create/email/verify',
    createSMSCode: API_PREFIX + '/user/create/sms/code',
    createSMSUserVerify: API_PREFIX + '/user/create/sms/verify',
    myInfo: API_PREFIX + '/user/info',
    loginUser: API_PREFIX + '/user/login',
    updateToken: API_PREFIX + '/user/token/update',
    updateUserInfo: API_PREFIX + '/user/update',
    updatePassword: API_PREFIX + '/user/password/update',
    updatePasswordEmailCode: API_PREFIX + '/user/password/update/email/code',
    deleteUser: API_PREFIX + '/user/delete',
    createUserByGitHub: API_PREFIX + '/user/create/github',
    createUserByGoogle: API_PREFIX + '/user/create/google',
    bindGitHub: API_PREFIX + '/user/bind/github',
    bindGoogle: API_PREFIX + '/user/bind/google',
    bindPhoneCode: API_PREFIX + '/user/bind/phone/code',
    bindPhoneVerify: API_PREFIX + '/user/bind/phone/verify',
    bindEmailCode: API_PREFIX + '/user/bind/email/code',
    bindEmailVerify: API_PREFIX + '/user/bind/email/verify',
    unBindEmail: API_PREFIX + '/user/unbind/email',
    unBindPhone: API_PREFIX + '/user/unbind/phone',
    unBindGitHub: API_PREFIX + '/user/unbind/github',
    unBindGoogle: API_PREFIX + '/user/unbind/google',
} 